Indexes/Table_of_Contents.md
Proofs/ng-kl.md

New proof. Title: "Kullback-Leibler divergence for the normal-gamma distribution".

added proof "ng-kl"

---

Indexes/Table_of_Contents.md
Proofs/glm-mle.md

New proof. Title: "Maximum likelihood estimation for the general linear model".

added proof "glm-mle"

---

Indexes/Table_of_Contents.md
Proofs/rsq-der.md

New proof. Title: "Derivation of R^2 and adjusted R^2".

added proof "rsq-der"

---

Indexes/Table_of_Contents.md
Proofs/blr-post.md

New proof. Title: "Posterior distribution for Bayesian linear regression".

added proof "blr-post"

---

Indexes/Table_of_Contents.md
Proofs/blr-lme.md

New proof. Title: "Log model evidence for Bayesian linear regression".

added proof "blr-lme"

---

Indexes/Table_of_Contents.md
Proofs/bayes-rule.md

New proof. Title: "Bayes' rule".

added proof "bayes-rule"

---

Indexes/Table_of_Contents.md
Proofs/lme-der.md

New proof. Title: "Derivation of the log model evidence".

added proof "lme-der"

---

Indexes/Table_of_Contents.md
Proofs/rsq-mll.md

New proof. Title: "Relationship between R² and maximum log-likelihood".

added proof "rsq-mll"

---

Indexes/Table_of_Contents.md
Proofs/norm-med.md

New proof. Title: "Median of the normal distribution".

added proof "norm-med"

---

Indexes/Table_of_Contents.md
Proofs/norm-mode.md

New proof. Title: "Mode of the normal distribution".

added proof "norm-mode"

---

Indexes/Table_of_Contents.md
Proofs/norm-var.md

New proof. Title: "Variance of the normal distribution".

added proof "norm-var"

---

Indexes/Table_of_Contents.md
Proofs/dmi-mce.md

New proof. Title: "Relation of mutual information to marginal and conditional entropy".

added proof "dmi-mce"

---

Indexes/Table_of_Contents.md
Proofs/dmi-mje.md

New proof. Title: "Relation of mutual information to marginal and joint entropy".

added proof "dmi-mje"

---

Indexes/Table_of_Contents.md
Proofs/dmi-jce.md

New proof. Title: "Relation of mutual information to joint and conditional entropy".

added proof "dmi-jce"

---

Indexes/Table_of_Contents.md
Proofs/bern-mean.md
Proofs/bin-mean.md
Proofs/cat-mean.md
Proofs/mult-mean.md

New proofs. Titles: see files.

added four proofs

---

Indexes/Table_of_Contents.md
Proofs/matn-mvn.md

New proof. Title: "Equivalence of matrix-normal distribution and multivariate normal distribution".

added proof "matn-mvn"

---

Indexes/Table_of_Contents.md
Proofs/poiss-mle.md

New proof. Title: "Maximum likelihood estimation for Poisson-distributed data".

added proof "poiss-mle"

---

Indexes/Table_of_Contents.md
Proofs/beta-mom.md

New proof. Title: "Method of moments for beta-distributed data".

added proof "beta-mom"

---

I/Table_of_Contents.md
P/bin-post.md

New proof. Title: "Posterior distribution for binomial observations".

added proof "bin-post"

---

I/Table_of_Contents.md
P/bin-lme.md

New proof. Title: "Log model evidence for binomial observations".

added proof "bin-lme"

---

I/Table_of_Contents.md
P/bic-der.md

New proof. Title: "Derivation of the Bayesian information criterion".

added proof "bic-der"

---

D/cuni.md
D/matn.md
D/ng.md
D/norm.md
I/Table_of_Contents.md
P/mvn-pdf.md
P/norm-pdf.md

4 new definitions and 2 new proofs. Titles: see files.

added new content

---

I/Table_of_Contents.md
P/cuni-pdf.md

New proof. Title: "Probability density function of the continuous uniform distribution".

added proof "cuni-pdf"

---

I/Table_of_Contents.md
P/mlr-ols2.md

New proof. Title: "Ordinary least squares for multiple linear regression".

added proof "mlr-ols2"

---

I/Table_of_Contents.md
P/poissexp-lme.md
P/poissexp-post.md
P/poissexp-prior.md

New proofs. Titles: see files.

added 3 proofs

---

I/Table_of_Contents.md
P/exp-mean.md

New proof. Title: "Mean of the exponential distribution".

added proof "exp-mean"

---

I/Table_of_Contents.md
P/exp-cdf.md
P/exp-med.md

New proofs. Titles: see files.

added 2 proofs

---

D/bf.md
P/sddr-bf.md

This is my first contribution of several I have planned.  But, I wanted to do this one first by itself to make sure I have the workflow down correctly! :)

added "bf" and "sddr-bf"

---

D/wald.md
P/bf-ep.md
P/wald-pdf.md

I'm now starting to add some work on the Wald distribution.  I'll have theorems about CDF, mean, and variance soon!

add wald and wald-pdf

---

P/bf-tran.md

just one addition this time...a simple theorem about transitivity of Bayes factors.

add [bf-tran]

---

P/wald-mean.md
P/wald-mgf.md
P/wald-var.md

I've added three new theorems for the Wald distribution.

add [wald-mgf, wald-mean, wald-var]

---

D/chi-2.md
P/chi-2-gam.md
P/mom-chi-2.md

I have added a definition of chi-square distribution and two related theorems.

added [chi-2, chi-2-gam, mom-chi-2]

---

D/lognorm.md
P/lognorm-med.md

A first PR for just the lognormal definition and lognormal median proof, would like to add additional lognormal definitions & proofs later too

add lognormal definition & lognormal median proof

---

P/exp-mode.md

Updated Proof for mode of exponential distribution

---

P/mult-cov.md

is there a way to preview the whole book after making own changes? The markdown module in VS Code does not allow me to check if e.g. all the links to other chapters are coded correctly...

added section on the covariance matrix of a random vector with a multinomial distribution

---

D/sr.md

Overall, I plan to add definitions for scoring rules, proper scoring rules, and strictly proper scoring rules. Also, I plan to add a couple of proofs that show commonly used scoring rules (log probability, brier, cross-entropy, etc.) are strictly proper. This pr includes a **definition for scoring rule**.

added def sr

---

D/psr.md

Hotfix on proper scoring rule - removed the max operation on the right hand side.

hotfix on 'psr'

---

D/bsr.md
P/lpsr-spsr.md

Definition for Brier Scoring rule is added.

added def bsr

---

I/ToC.md
P/mean-ls.md

Added proof that the expected value minimizes the expected squared distance (squared error).

added "mean-ls"

---

I/ToC.md
P/med-mae.md

As promised, adds a proof that the median minimizes the mean absolute error. Happy to make any other changes or fixes needed upon review.

add median minimizes MAE

---

P/ugkv-lme.md

Expanding the derivation of p(y, \mu) and adding the missing parameter \mu_n on the next line of the proof

Update ugkv-lme.md to give more steps for derivation of p(y, \mu)
